In [14]:
import numpy as np
np.set_printoptions(legacy="1.13")

In [16]:
array = np.array(list(map(float,input().split())))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


In [17]:
np.floor(array)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [18]:
np.ceil(array)

array([  2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [19]:
np.rint(array)

array([  1.,   2.,   3.,   4.,   6.,   7.,   8.,   9.,  10.])